version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "8080:8080"
    networks: 
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge